version: "3.2"
services:
  flask:
    build: .
    restart: always
    ports:
      - "80:8080"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["runuser", "-u", "myuser", "--", "python", "-m", "flask", "--debug", "run", "--host=0.0.0.0"]
    volumes:
      - .:/home/myuser